### ISSUE TITLE
OF 0.9.3

### ISSUE THREAD

**Issue by antimodular** [gameoverhack/ofxThreadedVideo#10]
amazing addon.
i am running 100 128x64 files at the same time on OF 0.9.0 on OS X 10.10.5.

do you know what it would take to make it work with OF 0.9.3? All my other parts are written in 0.9.3.

also, quicktime is 64-bit if i am not mistaken. why the need to compile again 32-bit?

thanks a bunch.

**Comment by JoshuaBatty** [comment]
Quicktime is 32 bit unfortunately. AVFoundation is apples newer 64 big framework.

**Comment by antimodular** [comment]
@JoshuaBatty thanks. just learned about these 32-bit quicktime from here too:
https://developer.apple.com/library/mac/documentation/Darwin/Conceptual/64bitPorting/HighLevelAPIs/HighLevelAPIs.html#//apple_ref/doc/uid/TP40001064-CH224-SW6

Still hoping that this addon will work with OF 0.9.3 at some point. not so far though.

**Comment by antimodular** [comment]
i think it's an already reported bug in OF 0.9.3
https://github.com/openframeworks/openFrameworks/issues/4993

we will probably have to wait for OF 0.9.4 for this to work again.

**Comment by gameoverhack** [comment]
Latest version is now compatible with 10.9+ as long as the application is compiled as 32 bit
