### ISSUE TITLE
Linux compatibility

### ISSUE THREAD

**Issue by urshofer** [gameoverhack/ofxThreadedVideo#5]
Hi
did anybody test ofxThreadedVideo on linux? I'm running successfully an application with the old goThreadedVideo add-on. With the new add-on the movies don't run, they're standing still (like paused). I'm on the of-develop branch on a up to date ubuntu system. Although, the frames are counted correctly. Internally, the movies seems to run, but the texture is not updated.
Best
Urs Hofer

**Comment by gameoverhack** [comment]
Sorry it won't work on linux as it's based on Quicktime which only has SDKs for windows and osx
