### ISSUE TITLE
can't build examples with xcode 7 and ofx 0.8.4

### ISSUE THREAD

**Issue by batchku** [gameoverhack/ofxThreadedVideo#9]
hello all,
i fixed the initial problem of the wrong os x sdk indicated in the example projects, but am running into this error in complication:

no such file or directory: '/Users/ali/Documents/Development/of_v0.8.4_osx_release/addons/addons/ofxThreadedVideo/src/ofxThreadedVideo.cpp'

i see that the path isn't right (double /addons) but not sure how to fix it.  any ideas?

**Comment by gameoverhack** [comment]
Latest version is now compatible with 10.9+ as long as the application is compiled as 32 bit
